#!/usr/bin/env bash
# PreToolUse hook (Edit|Write|MultiEdit|NotebookEdit): enforce path tiers.
#
# Red paths are blocked: secrets, agent control files, lockfiles, and any
# file outside the project (temp dirs excepted). Yellow paths pass here;
# yellow-notice.sh flags them after the edit.
set -uo pipefail
. "$(dirname "$0")/lib/common.sh"
. "$(dirname "$0")/lib/policy.sh"

fw_read_input
fw_enter_project

if [ "$FW_HAS_JQ" = 1 ]; then
  path=$(fw_get '.tool_input.file_path // .tool_input.notebook_path // .tool_input.path')
else
  # Fail closed for the obvious Red cases when jq is missing.
  path=$(printf '%s' "$FW_INPUT" | sed -nE 's/.*"(file_path|notebook_path)"[[:space:]]*:[[:space:]]*"([^"]*)".*/\2/p' | head -1)
fi
[ -z "$path" ] && exit 0

tier=$(fw_path_tier "$path")
case "$tier" in
  red*)
    fw_block "Blocked by protected-paths: $(fw_relpath "$(fw_abspath "$path")") is a ${tier#red } path.
Agents do not edit this file. If the task needs the change, record it under Blocked with the exact edit, so a human can make it."
    ;;
esac
exit 0
